### ISSUE TITLE
Unable to install vue admin

### ISSUE THREAD

**Issue by cooltaby** [smart-test-ti/solox-vue-admin#1]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] **bug report**
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Bug
* **What is the current behavior?**
Unable to install the vue admin using npm install and yarn install commands getting lots of erros shared below
* **If the current behavior is a bug, please provide the steps to reproduce, ideally also a screenshot or gif if it's a style issue**

* **What is the expected behavior?**
User should be able to install using command npm install without any issue
* **What is the motivation / use case for changing the behavior?**

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
Logs:
D:\admin\myproject>npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: epic-spinners@1.1.0
npm ERR! Found: vue@3.2.11
npm ERR! node_modules/vue
npm ERR!   vue@"^3.2.0" from the root project
npm ERR!   peer vue@"^3.2.0" from element-plus@2.2.9
npm ERR!   node_modules/element-plus
npm ERR!     element-plus@"^2.2.9" from the root project
npm ERR!   13 more (vue-demi, vue-flatpickr-component, vue-gtm, vue-i18n, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vue@"^2.5.2" from epic-spinners@1.1.0
npm ERR! node_modules/epic-spinners
npm ERR!   epic-spinners@"^1.1.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: vue@2.7.14
npm ERR! node_modules/vue
npm ERR!   peer vue@"^2.5.2" from epic-spinners@1.1.0
npm ERR!   node_modules/epic-spinners
npm ERR!     epic-spinners@"^1.1.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\x\AppData\Local\npm-cache\_logs\2023-08-24T14_54_50_267Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: C:\Users\x\AppData\Local\npm-cache\_logs\2023-08-24T14_54_50_267Z-debug-0.log

**Comment by cooltaby** [comment]
Please update your dependency and share a guide how to install and use it with solox tool, thanks for your nice work.

**Comment by cooltaby** [comment]
Logs with Yan for command **yarn serve**  **yarn build**  **yarn build --report**


D:\admin\myprojecT1>yarn serve
yarn run v1.22.19
$ vue-cli-service serve
 INFO  Starting development server...
10% building 2/5 modules 3 active ...cT1\node_modules\eslint-loader\index.js??ref--13-0!D:\admin\myprojecT1\src\main.tsError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\admin\myprojecT1\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\admin\myprojecT1\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\admin\myprojecT1\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\admin\myprojecT1\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\admin\myprojecT1\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (D:\admin\myprojecT1\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at D:\admin\myprojecT1\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\admin\myprojecT1\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\admin\myprojecT1\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\admin\myprojecT1\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\admin\myprojecT1\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\admin\myprojecT1\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (D:\admin\myprojecT1\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at D:\admin\myprojecT1\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at D:\admin\myprojecT1\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.15.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

yarn run v1.22.19T1>yarn build
$ vue-cli-service build

|  Building for production...Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\admin\myprojecT1\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\admin\myprojecT1\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\admin\myprojecT1\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\admin\myprojecT1\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\admin\myprojecT1\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (D:\admin\myprojecT1\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at D:\admin\myprojecT1\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
|  Building for production...D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:114
                        throw e;
                        ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\admin\myprojecT1\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\admin\myprojecT1\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\admin\myprojecT1\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\admin\myprojecT1\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\admin\myprojecT1\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at context.callback (D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\admin\myprojecT1\node_modules\cache-loader\dist\index.js:147:7
    at D:\admin\myprojecT1\node_modules\graceful-fs\graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:198:23) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.15.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

D:\admin\myprojecT1>yarn build --report
yarn run v1.22.19
$ vue-cli-service build --report

|  Building for production...Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\admin\myprojecT1\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\admin\myprojecT1\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\admin\myprojecT1\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\admin\myprojecT1\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\admin\myprojecT1\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (D:\admin\myprojecT1\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at D:\admin\myprojecT1\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
/  Building for production...D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:114
                        throw e;
                        ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\admin\myprojecT1\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\admin\myprojecT1\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\admin\myprojecT1\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\admin\myprojecT1\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\admin\myprojecT1\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:186:6
    at context.callback (D:\admin\myprojecT1\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\admin\myprojecT1\node_modules\cache-loader\dist\index.js:240:7
    at D:\admin\myprojecT1\node_modules\neo-async\async.js:2830:7
    at done (D:\admin\myprojecT1\node_modules\neo-async\async.js:2865:11)
    at D:\admin\myprojecT1\node_modules\neo-async\async.js:2818:7
    at D:\admin\myprojecT1\node_modules\cache-loader\dist\index.js:229:9 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.15.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

D:\admin\myprojecT1>`

@rafa0128

**Comment by cooltaby** [comment]
Issue was resolved after downgrading [Node.js](https://nodejs.org/en/) ( =14.*)  but still unclear how to use it with solox , how to connect and create user accounts

**Comment by rafa0128** [comment]
just a demo, you can continue to develop it
